# Generated by Django 5.0 on 2024-04-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
